//===----------------------------------------------------------------------===//
//
// This source file is part of the Soto for AWS open source project
//
// Copyright (c) 2017-2021 the Soto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Soto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by https://github.com/soto-project/soto/tree/main/CodeGenerator. DO NOT EDIT.

import SotoCore

/// Error enum for Route53RecoveryCluster
public struct Route53RecoveryClusterErrorType: AWSErrorType {
    enum Code: String {
        case accessDeniedException = "AccessDeniedException"
        case conflictException = "ConflictException"
        case endpointTemporarilyUnavailableException = "EndpointTemporarilyUnavailableException"
        case internalServerException = "InternalServerException"
        case resourceNotFoundException = "ResourceNotFoundException"
        case throttlingException = "ThrottlingException"
        case validationException = "ValidationException"
    }

    private let error: Code
    public let context: AWSErrorContext?

    /// initialize Route53RecoveryCluster
    public init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    internal init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// return error code string
    public var errorCode: String { self.error.rawValue }

    /// You don't have sufficient permissions to query the routing control state.
    public static var accessDeniedException: Self { .init(.accessDeniedException) }
    /// There was a conflict with this request. Try again.
    public static var conflictException: Self { .init(.conflictException) }
    /// The cluster endpoint isn't available. Try another cluster endpoint.
    public static var endpointTemporarilyUnavailableException: Self { .init(.endpointTemporarilyUnavailableException) }
    /// There was an unexpected error during processing of the request.
    public static var internalServerException: Self { .init(.internalServerException) }
    /// The request references a routing control that was not found.
    public static var resourceNotFoundException: Self { .init(.resourceNotFoundException) }
    /// The request was denied because of request throttling.
    public static var throttlingException: Self { .init(.throttlingException) }
    /// There was a validation error on the request.
    public static var validationException: Self { .init(.validationException) }
}

extension Route53RecoveryClusterErrorType: Equatable {
    public static func == (lhs: Route53RecoveryClusterErrorType, rhs: Route53RecoveryClusterErrorType) -> Bool {
        lhs.error == rhs.error
    }
}

extension Route53RecoveryClusterErrorType: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(self.message ?? "")"
    }
}
